language: workflow

envs:
  global:
    variables:
      MVN_SETTINGS: .looper/settings.xml
      DEPLOYMENT_USERNAME: "%{credentials.username('walmart-deployment')}"
      DEPLOYMENT_PASSWORD: "%{credentials.password('walmart-deployment')}"

      # until we will be able to run docker images from mvn directly on a looper's slave
      CI_DB_HOST: "docker.dev.concord-ci.devtools.prod.walmart.com"
      CI_DB_USERNAME: "%{credentials.username('concordCiDb')}"
      CI_DB_PASSWORD: "%{credentials.password('concordCiDb')}"
      DOCKER_HOST: "tcp://docker.dev.concord-ci.devtools.prod.walmart.com:2375"
      DOCKER_API_VERSION: "1.22"

tools:
  jdk: 8
  maven: 3.3.9

flows:
  runsonar:
    - sonar("Sonar"):
      - (name sonar) mvn -Plooper -e -B -fae $SONAR_MAVEN_GOAL

  build:
    - call: cleanup
    - (name build) mvn -U -B -s $MVN_SETTINGS clean install -Plooper

  build_and_deploy:
    - call: cleanup
    - (name build) mvn -U -B -s $MVN_SETTINGS clean deploy -Plooper

  cleanup:
    - (name cleanup) docker rm -f $(docker ps -aq) &> /dev/null || true

  default:
    - call: build_and_deploy
    - call: runsonar

  pr:
    - call: build