tools:
  jdk:
  - 8
  maven:
  - 3.3.9

flows:
  default (on linux):
    - DOCKER_HOST=tcp://localhost:2375 mvn clean install -Plooper -Pit -Pdocker -Ddocker.host.addr=`/sbin/ip -o -4 addr list | grep docker0 | sed 's/.*inet //;s/\/.*//'`
