sudo: required

language: java
jdk:
- oraclejdk8

python:
- 2.7

services:
- docker

cache:
  directories:
  - $HOME/.m2
  - console/node_modules

install: true
script:
- pip install --user grpcio-tools
- mvn install -Pdocker -Pit -B
