flows:
  onChange:
  - log: "Refreshing triggers..."
  - task: triggersRefresh
    in:
      repository: ${event.repository}
      project: ${event.project}

  - log: "Refreshing LPs..."
  - task: landingPageRefresh
    in:
      repository: ${event.repository}
      project: ${event.project}

triggers:
  - concord:
      event: "repository.*"
      entryPoint: "onChange"

  - github:
      entryPoint: "onChange"
