flows:
  onPush:
  - task: triggersRefresh
    in:
      repository: ${event.repository}
      project: ${event.project}
  - task: landingPageRefresh
    in:
      repository: ${event.repository}
      project: ${event.project}

configuration:
  arguments:
    name: "Concord"
    concord:
      apiKey: "auBy4eDWrKWsyhiDp3AQiw"
  dependencies:
  - "mvn://com.walmartlabs.concord.plugins:concord-tasks:0.35.0"

triggers:
  - github:
      repository: ".*"
      branch: ".*"
      entryPoint: onPush
