configuration:
  entryPoint: main
  # to use `ansible2` task
  dependencies:
    - "http://nexus.prod.walmart.com/nexus/service/local/repo_groups/devtools-public/content/com/walmartlabs/concord/plugins/basic/ansible-tasks/0.38.0/ansible-tasks-0.38.0.jar"
  arguments:
    ansibleParams:
      playbook: playbook/hello.yml
      inventory:
        local:
          hosts:
            - "127.0.0.1"
          vars:
            ansible_connection: "local"
      extraVars:
        greetings: "Hi there!"


flows:
  main:
    - ${ansible2.run(ansibleParams, __attr_localPath)}
