configuration:
  dependencies:
  - "mvn://com.walmartlabs.concord.plugins.basic:ansible-tasks:0.47.0"

flows:
  default:
  - task: ansible
    in:
      playbook: playbook/hello.yml
      verbose: 3
      user: "ibodrov"
      config:
        ssh_connection:
          pipelining: false
      privateKey:
        secretName: "ibTestSecret"
        password: "q1"
      inventory:
        local:
          hosts:
            - "10.227.235.190"
      extraVars:
        greetings: "Hi there!"
