variables:
  entryPoint: main

  # to use `ansible2` task
  dependencies:
  - "http://nexus.prod.walmart.com/nexus/service/local/repo_groups/devtools-public/content/com/walmartlabs/concord/plugins/basic/ansible-tasks/0.36.0/ansible-tasks-0.36.0.jar"

  arguments:
    # default values
    myForm:
      myMessage: "Hello, Concord"

flows:
  main:
  # open the form
  - form: myForm

  # call the playbook
  - task: ansible2
    in:
      playbook: playbook/hello.yml
      inventory:
        local:
          hosts:
          - "127.0.0.1"
          vars:
            ansible_connection: "local"
      extraVars:
        # pass the form field's value into the playbook
        message: ${myForm.myMessage}

forms:
  myForm:
    - myMessage: { type: "string" }
