flows:
  onChange:
  - log: "refreshing triggers"
  - task: triggersRefresh
    in:
      repository: ${event.repository}
      project: ${event.project}
  - log: "refreshing LP"
  - task: landingPageRefresh
    in:
      repository: ${event.repository}
      project: ${event.project}

triggers:
  - concord:
      event: "repository.*"
      entryPoint: "onChange"

  - github:
      repository: ".*"
      branch: ".*"
      entryPoint: "onChange"

configuration:
  dependencies:
  - "mvn://com.walmartlabs.concord:concord-client:${project.version}"
