flows:
  main:
  # working with SSH key pairs
  - set:
      myKey: ${crypto.exportKeyAsFile('myKey', pwd)}

  - log: "Public key file: ${myKey.public}"
  - log: "Private key file: ${myKey.private}"

  # working with username/password credentials
  - log: "Credentials: ${crypto.exportCredentials('myCreds', pwd)}"

  # working with encrypted strings
  - log: "Plain secret: ${crypto.exportAsString('myValue', pwd)}"

configuration:
  entryPoint: main
  arguments:
    # alternatively, a form, an encrypted value or an external
    # service can be used to retrieve the password
    pwd: "12345678"
