flows:
  onPush:
  - task: triggersRefresh
    in:
      repository: ${event.repository}
      project: ${event.project}
  - task: landingPageRefresh
    in:
      repository: ${event.repository}
      project: ${event.project}

triggers:
  - github:
      repository: ".*"
      branch: ".*"
      entryPoint: onPush

configuration:
  dependencies:
  - "mvn://com.walmartlabs.concord:concord-client:${project.version}"
