flows:
  main:
  - script: groovy
    body: |
      import static groovyx.net.http.HttpBuilder.configure

      def http = configure {
        request.uri = "http://localhost:8001"
      }

      Map result = http.get(Map) {
        request.uri.path = "/api/v1/server/version"
      }

      execution.setVariable("serverVersion", result["version"])

  - log: "Server's version: ${serverVersion}"

configuration:
  entryPoint: main
  dependencies:
  - "http://nexus.prod.walmart.com/nexus/content/repositories/public/org/codehaus/groovy/groovy-all/2.4.11/groovy-all-2.4.11.jar"
  - "http://nexus.prod.walmart.com/nexus/content/repositories/public/io/github/http-builder-ng/http-builder-ng-core/0.16.1/http-builder-ng-core-0.16.1.jar"
  - "http://nexus.prod.walmart.com/nexus/content/repositories/public/xml-resolver/xml-resolver/1.2/xml-resolver-1.2.jar"
