flows:
  onChange:
  - log: "Refreshing triggers... ${event}"
  - task: triggersRefresh
    in:
      org: ${event.org}
      repository: ${event.repository}
      project: ${event.project}

  - log: "Refreshing LPs... ${event}"
  - task: landingPageRefresh
    in:
      org: ${event.org}
      repository: ${event.repository}
      project: ${event.project}

triggers:
  - concord:
      event: "repository.*"
      entryPoint: "onChange"

  - github:
      org: ".*"
      project: ".*"
      repository: ".*"
      type: "push"
      entryPoint: "onChange"
