flows:
  onChange:
  - log: "Refreshing repository... ${event}"
  - task: repositoryRefresh
    in:
      org: ${event.org}
      repository: ${event.repository}
      project: ${event.project}

triggers:
  - concord:
      event: "repository.*"
      entryPoint: "onChange"

  - github:
      org: ".*"
      project: ".*"
      repository: ".*"
      type: "push"
      unknownRepo: false
      entryPoint: "onChange"
