configuration:
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins.basic:ansible-tasks:0.43.0"
    - "mvn://com.walmartlabs.concord.plugins:concord-tasks:0.33.1-SNAPSHOT"
  arguments:
    newVersion:
      version: "1.0.0"
    concord:
      baseUrl: "http://localhost:8001"
      apiKey: "auBy4eDWrKWsyhiDp3AQiw"

flows:
  default:
  - task: ansible2
    in:
      inventory: ${inventory.query('myInventory', 'myQuery', newVersion)}
      playbook: playbook/hello.yml
      extraVars:
        greetings: "Hi there!"