configuration:
  entryPoint: main
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins.basic:ansible-tasks:0.43.0"
    - "file:///Users/brig/prj/wallmart/concord-plugins/tasks/concord/target/concord-tasks-0.33.1-SNAPSHOT.jar"
  arguments:
    newVersion:
      version: "1.0.0"
    concord:
      baseUrl: "http://localhost:8001"
      apiKey: "auBy4eDWrKWsyhiDp3AQiw"

flows:
  main:
  - task: ansible2
    in:
      inventory: ${inventory.query('myInventory', 'myQuery', newVersion)}
      playbook: playbook/hello.yml
      extraVars:
        greetings: "Hi there!"