configuration:
  dependencies:
    - "mvn://com.walmartlabs.concord.plugins.basic:ansible-tasks:0.43.0"
    - "mvn://com.walmartlabs.concord.plugins:concord-tasks:0.33.1-SNAPSHOT"
  arguments:
    inventoryQueryParams:
      facter_zypper_version: "1.6.333"
    inventoryVars:
      ansible_connection: "local"
    concord:
      baseUrl: "http://localhost:8001"
      apiKey: "auBy4eDWrKWsyhiDp3AQiw"

flows:
  default:
  - task: ansible2
    in:
      inventory: ${inventory.ansible('myInventory', 'myHostsGroup', 'endpointsByZypperVersion', inventoryQueryParams, inventoryVars)}
      playbook: playbook/hello.yml
      extraVars:
        greetings: "Hi there!"