configuration:
  dependencies:
  - "mvn://com.walmartlabs.concord.plugins.basic:ansible-tasks:0.48.0"
  arguments:
    myVars:
      ansible_connection: "local"
    concord:
      apiKey: "iCKnYBTPCbaikaRV6GdJDw" # user "demo"

flows:
  default:
  - task: ansible
    in:
      # arguments: inventory name, ansible host group name, query name, query params, additional inventory variables
      inventory: "${inventory.ansible('Default', 'myInventory', 'myHostsGroup', 'endpointsByZypperVersion', {'facter_zypper_version': '1.6.333'}, myVars)}"
      # will produce a JSON structure like this:
      # {
      #   "myHostsGroup": {
      #     "hosts": ["55.193.40.129"],
      #     "vars": {
      #       "ansible_connection": "local"
      #     }
      #   }

      playbook: playbook/hello.yml
      extraVars:
        greetings: "Hi there!"