configuration:
  entryPoint: main

  # to use `ansible2` task
  dependencies:
  - "http://nexus.prod.walmart.com/nexus/service/local/repo_groups/devtools-public/content/com/walmartlabs/concord/plugins/basic/ansible-tasks/0.38.0/ansible-tasks-0.38.0.jar"

  # global ansible configuration
  ansible:
    privateKeys:
      - repository: ".*"
        secret: "mySecret"

  arguments:
    # local ansible arguments
    ansibleParams:
      # remote user
      user: "app"
      playbook: playbook/hello.yml
      inventory:
        local:
          hosts:
            - "192.168.0.108"
      extraVars:
        greetings: "Hi there!"

flows:
  main:
    - ${ansible2.run(ansibleParams, __attr_localPath)}
