flows:
  repositoryChanged:
  - log: "refreshing triggers"
  - task: triggersRefresh
    in:
      repository: ${event.repository}
      project: ${event.project}
  - log: "refreshing LP"
  - task: landingPageRefresh
    in:
      repository: ${event.repository}
      project: ${event.project}

triggers:
  - concord:
      event: "repository.*"
      entryPoint: "repositoryChanged"

configuration:
  dependencies:
  - "mvn://com.walmartlabs.concord:concord-client:${project.version}"
