configuration:
  entryPoint: main
  dependencies:
  - "http://nexus.prod.walmart.com/nexus/service/local/repo_groups/devtools-public/content/com/walmartlabs/concord/plugins/basic/ansible-tasks/0.39.0/ansible-tasks-0.39.0.jar"

flows:
  main:
  - task: ansible2
    in:
      # specify the docker image to use
      dockerImage: "docker.prod.walmart.com/walmartlabs/concord-ansible:latest"
      # rest of the parameters are the usual
      playbook: playbook/hello.yml
      inventory:
        local:
          hosts:
          - "127.0.0.1"
          vars:
            ansible_connection: "local"
      extraVars:
        greetings: "Hi there!"
